# Generated by Django 3.2.20 on 2023-08-10 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_before_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 20, 35, 7, 96116)),
        ),
    ]
