# Generated by Django 3.2.20 on 2023-08-24 14:18

import datetime
from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_product_best_before_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=market.models.uniq_name_upload),
        ),
        migrations.AlterField(
            model_name='product',
            name='best_before_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 20, 18, 38, 716373)),
        ),
    ]
